(() => {
  const cfg=window.SUPABASE_CONFIG||{}, LS="dpdp-platform-v4", GUEST="0x8acure-guest-progress";
  let sb=null, session=null;
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
  const toast=m=>{const e=document.getElementById("toast");if(!e)return;e.textContent=m;e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),2400)};
  const configured=!!(cfg.url&&cfg.anonKey&&window.supabase);
  function css(){if(document.getElementById("auth-css"))return;const s=document.createElement("style");s.id="auth-css";s.textContent=`
.auth-button{border:1px solid var(--line);background:var(--panel);color:var(--text);border-radius:10px;padding:8px 11px;font-size:12px;font-weight:700}.auth-button:hover{border-color:var(--cyan)}
.auth-modal{position:fixed;inset:0;z-index:200;display:grid;place-items:center;padding:18px;background:rgba(2,6,12,.78);backdrop-filter:blur(12px)}.auth-card{width:min(500px,100%);max-height:calc(100vh - 36px);overflow:auto;border:1px solid var(--line);background:var(--panel);border-radius:18px;padding:24px;box-shadow:var(--shadow)}.auth-card h2{margin:0 0 8px}.auth-card p{color:var(--muted);line-height:1.6;font-size:13px}.auth-form{display:grid;gap:10px;margin-top:16px}.auth-form label{font-size:12px;color:var(--muted)}.auth-form input{width:100%;margin-top:5px;border:1px solid var(--line);background:var(--panel2);color:var(--text);border-radius:10px;padding:11px 12px}.auth-row{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.auth-error{color:#fda4af;font-size:12px;min-height:18px}.privacy-box{border:1px solid var(--line);border-radius:12px;padding:12px;margin-top:12px;font-size:12px;line-height:1.6;color:var(--muted)}.privacy-box a{color:#7dd3fc}.auth-check{display:flex;gap:9px;align-items:flex-start;margin-top:12px;font-size:12px;color:var(--muted)}.auth-check input{width:18px;height:18px;flex:0 0 auto}.account-panel{max-width:760px;margin:24px auto}.account-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.account-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:18px}@media(max-width:640px){.account-grid{grid-template-columns:1fr}}
`;document.head.appendChild(s)}
  function nav(){const a=document.querySelector(".nav-actions");if(!a)return;let b=document.getElementById("auth-nav");if(!b){b=document.createElement("button");b.id="auth-nav";a.prepend(b)}b.className="auth-button";b.type="button";b.onclick=()=>session?account():open("login");updateNav()}
  function updateNav(){const a=document.querySelector(".nav-actions");const b=document.getElementById("auth-nav");if(b){b.textContent=session?"Account":"Sign in";b.setAttribute("aria-label",session?"Open account":"Sign in")}if(a&&window.DPDP_AUTH?.isAdmin&&!document.getElementById("admin-nav")){const x=document.createElement("button");x.id="admin-nav";x.className="auth-button";x.textContent="Admin";x.onclick=()=>window.DPDP_ADMIN?.open();a.prepend(x)}if(a&&!window.DPDP_AUTH?.isAdmin)document.getElementById("admin-nav")?.remove()}
  function loginIdentity(value){const v=String(value||"").trim().toLowerCase();return v==="admin"?"admin@0x8acure.local":v}
  function modal(html){document.getElementById("auth-modal")?.remove();const d=document.createElement("div");d.id="auth-modal";d.className="auth-modal";d.innerHTML=html;document.body.appendChild(d)}
  function privacy(){document.getElementById("app").innerHTML=`<section class="panel account-panel"><div class="eyebrow">0x8Acure · Privacy</div><h1>Privacy Notice</h1><p><b>What we collect:</b> name and email for authenticated accounts. Supabase also processes technical authentication and session data needed to secure sign-in.</p><p><b>Why:</b> account security, learning-progress synchronization, badges, and certificate administration or verification where applicable.</p><p><b>Guest mode:</b> learning can be used without an account. Guest progress remains in this browser until you choose to create an account and merge it.</p><p><b>Your choices:</b> account creation uses an explicit, unticked consent checkbox. You can download your account data or delete your account from Account.</p><p><b>Minimisation:</b> organization, phone, photo, advertising identifiers, and other optional profile data are not required.</p><p><b>Security:</b> user tables use Supabase Row Level Security. The browser receives only the publishable/anon key. Secret keys are server-side only.</p><p><b>Legal note:</b> this platform's notice should be reviewed against its actual processing and current applicable DPDP requirements before production use. It is not legal advice.</p><button class="btn primary" data-action="home">Back to learning</button></section>`}
  function open(mode="login"){
    if(!configured){toast("Supabase is not configured. Add supabase-config.js values.");return}
    modal(`<section class="auth-card" role="dialog" aria-modal="true" aria-labelledby="auth-title"><button class="btn ghost" id="auth-close" style="float:right">Close</button><div class="eyebrow">0x8Acure · Account</div><h2 id="auth-title">${mode==="signup"?"Create account":"Welcome back"}</h2><p>${mode==="signup"?"Save progress across devices. Only name and email are required.":"Sign in to sync your learning progress."}</p><form id="auth-form" class="auth-form">${mode==="signup"?'<label>Name<input id="auth-name" autocomplete="name" maxlength="120" required></label>':""}<label>${mode==="login"?"Email or username":"Email"}<input id="auth-email" type="${mode==="login"?"text":"email"}" autocomplete="${mode==="login"?"username":"email"}" placeholder="${mode==="login"?"you@example.com or admin":"you@example.com"}" required></label><label>Password<input id="auth-password" type="password" autocomplete="${mode==="signup"?"new-password":"current-password"}" minlength="8" required></label>${mode==="signup"?'<label class="auth-check"><input id="auth-consent" type="checkbox" required><span>I have read the <a href="#" id="privacy-link">Privacy Notice</a> and explicitly consent to the processing described there.</span></label>':""}<div id="auth-error" class="auth-error" aria-live="polite"></div><button class="btn primary" type="submit">${mode==="signup"?"Create account":"Sign in"}</button></form><div class="auth-row"><button class="btn ghost" id="google-auth" type="button">Continue with Google</button>${mode==="login"?'<button class="btn ghost" id="reset-auth" type="button">Forgot password?</button>':""}<button class="btn ghost" id="switch-auth" type="button">${mode==="signup"?"I already have an account":"Create an account"}</button><button class="btn ghost" id="guest-auth" type="button">Continue as guest</button></div><div class="privacy-box"><b>Privacy Notice</b><br>Name and email are used for account creation, security, progress synchronization, and certificate administration/verification where applicable. You can use guest mode without an account.</div></section>`);
    document.getElementById("auth-close").onclick=()=>document.getElementById("auth-modal")?.remove();
    document.getElementById("switch-auth").onclick=()=>open(mode==="signup"?"login":"signup");
    document.getElementById("guest-auth").onclick=()=>document.getElementById("auth-modal")?.remove();
    document.getElementById("google-auth").onclick=google;
    const reset=document.getElementById("reset-auth");if(reset)reset.onclick=resetPassword;
    const pl=document.getElementById("privacy-link");if(pl)pl.onclick=e=>{e.preventDefault();privacy()};
    document.getElementById("auth-form").onsubmit=e=>submit(e,mode);
  }
  async function submit(e,mode){e.preventDefault();const er=document.getElementById("auth-error");er.textContent="";try{
    if(mode==="signup"){if(!document.getElementById("auth-consent").checked)throw Error("Explicit consent is required.");const name=document.getElementById("auth-name").value.trim(),email=document.getElementById("auth-email").value.trim().toLowerCase(),password=document.getElementById("auth-password").value,consentAt=new Date().toISOString();const {data,error}=await sb.auth.signUp({email,password,options:{data:{name,consent_at:consentAt,privacy_version:"2026-09-30"},emailRedirectTo:location.href.split("#")[0]}});if(error)throw error;localStorage.setItem("0x8acure-signup-consent",consentAt);if(data.session){await finish(data.user,name,consentAt);document.getElementById("auth-modal")?.remove()}else{document.getElementById("auth-modal")?.remove();toast("Account created. Verify your email before signing in.")}}
    else{const {data,error}=await sb.auth.signInWithPassword({email:loginIdentity(document.getElementById("auth-email").value),password:document.getElementById("auth-password").value});if(error)throw error;await finish(data.user);document.getElementById("auth-modal")?.remove()}}
    catch(x){er.textContent=x.message||"Authentication failed."}}
  async function google(){const existing=document.getElementById("google-consent");if(!existing){const p=document.querySelector("#auth-modal .privacy-box");const row=document.createElement("label");row.className="auth-check";row.innerHTML='<input id="google-consent" type="checkbox"><span>I have read the Privacy Notice and explicitly consent to account processing if this creates an account.</span>';p.before(row);toast("Review the notice and tick consent before continuing with Google.");return}if(!existing.checked){toast("Explicit consent is required for a new Google account.");return}localStorage.setItem("0x8acure-google-consent",new Date().toISOString());const {error}=await sb.auth.signInWithOAuth({provider:"google",options:{redirectTo:location.href.split("#")[0]}});if(error)toast(error.message)}
  async function resetPassword(){const email=loginIdentity(document.getElementById("auth-email")?.value);if(!email){document.getElementById("auth-error").textContent="Enter your email first.";return}const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.href.split("#")[0]});if(error)document.getElementById("auth-error").textContent=error.message;else{document.getElementById("auth-modal")?.remove();toast("If the account exists, a password reset email will be sent.")}}
  async function finish(user,suppliedName="",consentAt=""){
    if(!user)return;
    if(!user.email_confirmed_at&&!user.app_metadata?.provider?.includes("google")){toast("Please verify your email before using the account.");return}
    const q=await sb.from("profiles").select("id,name,email,role,consent_at").eq("id",user.id).maybeSingle();if(q.error)throw q.error;
    if(!q.data){
      const c=consentAt||user.user_metadata?.consent_at||localStorage.getItem("0x8acure-signup-consent")||localStorage.getItem("0x8acure-google-consent");
      if(!c){await sb.auth.signOut();open("signup");throw Error("Explicit consent is required before creating your platform profile.")}
      const name=suppliedName||user.user_metadata?.name||user.user_metadata?.full_name||user.email.split("@")[0];
      const adminEmail=user.email?.trim().toLowerCase()==="admin@0x8acure.local";
      const {error}=await sb.from("profiles").insert({id:user.id,name:adminEmail?"Platform Administrator":name,email:user.email,role:adminEmail?"admin":"learner",consent_at:c,privacy_version:"2026-09-30"});if(error)throw error;
      localStorage.removeItem("0x8acure-signup-consent");localStorage.removeItem("0x8acure-google-consent");await merge(user.id)
    }
    session=(await sb.auth.getSession()).data.session;window.DPDP_AUTH.role=(user.email?.trim().toLowerCase()==="admin@0x8acure.local")?"admin":(q.data?.role||"learner");window.DPDP_AUTH.isAdmin=window.DPDP_AUTH.role==="admin";updateNav();await load(user.id)
  }
  async function merge(uid){let raw=localStorage.getItem(GUEST)||localStorage.getItem(LS);if(!raw)return;let s;try{s=JSON.parse(raw)}catch{return}const rows=Object.entries(s.completed||{}).map(([room_id,v])=>({user_id:uid,room_id,completed:!!v,xp:0,attempts:0}));if(rows.length)await sb.from("room_progress").upsert(rows,{onConflict:"user_id,room_id"});const n=rows.length,b=["first-room","five-rooms","100-xp","path-runner"].filter((x,i)=>(i===0&&n>=1)||(i===1&&n>=5)||(i===2&&Number(s.xp||0)>=100)||(i===3&&n>=10));if(b.length)await sb.from("badges_earned").upsert(b.map(badge_id=>({user_id:uid,badge_id})),{onConflict:"user_id,badge_id"});localStorage.removeItem(GUEST)}
  async function load(uid){const {data,error}=await sb.from("room_progress").select("room_id,completed,xp").eq("user_id",uid);if(error)return;const s=JSON.parse(localStorage.getItem(LS)||"{}");s.completed=s.completed||{};for(const x of data||[])if(x.completed)s.completed[x.room_id]=true;localStorage.setItem(LS,JSON.stringify(s))}
  async function account(){if(!session){open("login");return}const {data}=await sb.from("profiles").select("name,email,role,consent_at,privacy_version").eq("id",session.user.id).single();document.getElementById("app").innerHTML=`<section class="panel account-panel"><div class="eyebrow">0x8Acure · Account</div><h1>My account</h1><div class="account-grid"><div class="panel"><b>Name</b><p>${esc(data?.name)}</p></div><div class="panel"><b>Email</b><p>${esc(data?.email)}</p></div></div><div class="privacy-box"><b>Role:</b> ${esc(data?.role)}<br><b>Consent recorded:</b> ${esc(data?.consent_at)}<br>Privacy notice version: ${esc(data?.privacy_version)}</div><div class="account-actions"><button class="btn primary" id="download-data">Download my data</button><button class="btn ghost" id="privacy-account">Privacy Notice</button><button class="btn ghost" id="signout-account">Sign out</button><button class="btn" id="delete-account" style="border-color:#6b2434;color:#fda4af">Delete my account</button></div></section>`;document.getElementById("download-data").onclick=download;document.getElementById("privacy-account").onclick=privacy;document.getElementById("signout-account").onclick=async()=>{await sb.auth.signOut();location.reload()};document.getElementById("delete-account").onclick=del}
  async function download(){try{const out={exported_at:new Date().toISOString(),user_id:session.user.id};for(const t of ["profiles","room_progress","task_submissions","badges_earned","certificates"]){const key=t==="profiles"?"id":"user_id";const {data,error}=await sb.from(t).select("*").eq(key,session.user.id);if(error)throw error;out[t]=data||[]}const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(out,null,2)],{type:"application/json"}));a.download="0x8acure-my-data.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(e){toast("Data download failed: "+e.message)}}
  async function del(){if(!confirm("Delete your 0x8Acure account and associated platform data? This cannot be undone."))return;const {error}=await sb.functions.invoke("delete-account",{body:{}});if(error){toast(error.message||"Account deletion failed.");return}await sb.auth.signOut();localStorage.removeItem(LS);localStorage.removeItem(GUEST);toast("Account deleted.");setTimeout(()=>location.reload(),400)}
  function recovery(){if(location.hash.includes("type=recovery")){setTimeout(()=>{modal(`<section class="auth-card" role="dialog" aria-modal="true"><div class="eyebrow">0x8Acure · Password reset</div><h2>Choose a new password</h2><form id="recovery-form" class="auth-form"><label>New password<input id="new-password" type="password" minlength="8" required></label><div id="recovery-error" class="auth-error"></div><button class="btn primary">Update password</button></form></section>`);document.getElementById("recovery-form").onsubmit=async e=>{e.preventDefault();const {error}=await sb.auth.updateUser({password:document.getElementById("new-password").value});if(error)document.getElementById("recovery-error").textContent=error.message;else{document.getElementById("auth-modal")?.remove();history.replaceState({},document.title,location.pathname);toast("Password updated.")}}},250)}}
  async function init(){css();nav();if(!configured){window.DPDP_AUTH={configured:false,open,privacy};return}sb=window.supabase.createClient(cfg.url,cfg.anonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});window.DPDP_AUTH={configured:true,client:sb,open,account,privacy,role:"learner",isAdmin:false};const {data}=await sb.auth.getSession();session=data.session;updateNav();recovery();sb.auth.onAuthStateChange(async(e,s)=>{session=s;updateNav();if(e==="PASSWORD_RECOVERY"){recovery();return}if(s&&e!=="INITIAL_SESSION")try{await finish(s.user)}catch(x){toast(x.message)}})}
  window.addEventListener("0x8acure:progress-changed",()=>{if(session)load(session.user.id)});
  window.addEventListener("load",init);
})();