import { FormEvent, useEffect, useMemo, useState } from "react";
import { Send, Users, Wifi } from "lucide-react";
import { api } from "../lib/api";
import { supabase, type AppUser } from "../lib/supabase";
import { useAuth } from "../auth/AuthProvider";
type Room={id:string;title:string;slug:string;topic:string};
type Message={id:string;room_id:string;user_id:string;content:string;created_at:string};
export function RoomsView(){
 const {session,user,openAuth}=useAuth();const [rooms,setRooms]=useState<Room[]>([]),[active,setActive]=useState<Room|null>(null),[messages,setMessages]=useState<Message[]>([]),[draft,setDraft]=useState(""),[error,setError]=useState(""),[sending,setSending]=useState(false);
 useEffect(()=>{api<{rooms:Room[]}>('/api/cyber/rooms').then(({rooms:list})=>{setRooms(list);setActive(list[0]||null);}).catch(e=>setError(e.message));},[]);
 useEffect(()=>{const client=supabase;if(!active||!client)return;let alive=true;client.from("cyber_room_messages").select("id,room_id,user_id,content,created_at").eq("room_id",active.id).order("created_at",{ascending:false}).limit(60).then(({data,error:queryError})=>{if(alive){if(queryError)setError("Could not load room history. Check Supabase table and RLS setup.");else setMessages(((data||[]) as Message[]).reverse());}});
  const channel=client.channel(`room:${active.id}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"cyber_room_messages",filter:`room_id=eq.${active.id}`},payload=>{const incoming=payload.new as Message;setMessages(current=>current.some(item=>item.id===incoming.id)?current:[...current,incoming].slice(-100));}).subscribe();
  return()=>{alive=false;void client.removeChannel(channel);};},[active?.id]);
 const send=async(event:FormEvent)=>{event.preventDefault();if(!draft.trim()||!active||sending)return;if(!session){openAuth();return;}if(!supabase){setError("Configure Supabase to enable room chat.");return;}setSending(true);setError("");const {error:insertError}=await supabase.from("cyber_room_messages").insert({room_id:active.id,user_id:user?.id,content:draft.trim().slice(0,2000)});if(insertError)setError("Message could not be sent. Confirm RLS and run supabase/cyber-security.sql.");else setDraft("");setSending(false);};
 const rendered=useMemo(()=>messages.map(message=>({message,own:message.user_id===user?.id})),[messages,user?.id]);
 return <section className="content-page"><div className="page-heading"><span className="eyebrow">LIVE COLLABORATION</span><h1>War Rooms</h1><p>Collaborate on defensive scenarios. Keep shared notes within authorized lab work.</p></div>{error&&<p role="status" className="form-message">{error}</p>}{!supabase&&<div className="notice">Set the Supabase frontend credentials and run the SQL setup to enable real-time chat.</div>}<div className="rooms-layout"><aside className="room-list panel"><div className="panel-title"><span>ROOM CHANNELS</span><span className="online-dot"/></div>{rooms.map(room=><button key={room.id} className={room.id===active?.id?"room-select active":"room-select"} onClick={()=>setActive(room)}><span className="room-hash">#</span><span><b>{room.title}</b><small>{room.topic}</small></span></button>)}{!rooms.length&&<p className="empty-note">Seed the database to create starter rooms.</p>}</aside><section className="room-chat panel" aria-label="Chat room"><header className="room-chat-header"><div><h2>{active?.title||"Choose a room"}</h2><span>{active?.topic||""}</span></div><span className="room-live"><Wifi size={15}/> LIVE</span></header><div className="message-list" aria-live="polite">{rendered.length?rendered.map(({message,own})=><article className={own?"message own":"message"} key={message.id}><div className="message-meta"><b>{own?(user?.username||"You"):`learner-${message.user_id.slice(0,6)}`}</b><time dateTime={message.created_at}>{new Date(message.created_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</time></div><MessageBody content={message.content}/></article>):<div className="chat-empty"><Users size={22}/><p>No messages yet. Start with a helpful note or question.</p></div>}</div><form className="message-compose" onSubmit={send}><label className="visually-hidden" htmlFor="message-draft">Message</label><textarea id="message-draft" rows={2} maxLength={2000} value={draft} onChange={event=>setDraft(event.target.value)} placeholder={session?"Share a note… (code fences supported)":"Sign in to join the discussion"} disabled={!active}/><button className="btn primary" disabled={!active||sending||!draft.trim()} aria-label="Send message"><Send size={16}/>Send</button></form></section></div></section>;
}
function MessageBody({content}:{content:string}){const parts=content.split(/```([\s\S]*?)```/g);return <div className="message-body">{parts.map((part,index)=>index%2?<pre key={index}><code>{part.replace(/^\w+\n/,"")}</code></pre>:<p key={index}>{part}</p>)}</div>}
